services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: products

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  produit-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-container
    restart: always
    ports:
      - 8084:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/products
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
